### ISSUE TITLE
Shift doubleclick does not work for mass insert

### ISSUE THREAD

**Issue by BBoldt** [elytra/CorrelatedPotentialistics#12]
Would be a useful feature. It's a pain slowly inserting a lot of a single item.

**Comment by LordHellscream** [comment]
Same issue here, I suspect this is a bug. Since shift-doubleclick does insert 2 stacks (so It seems its attempting to insert all the stack and is just broken somewhere)

**Comment by unascribed** [comment]
As I put in the tags, it is a bug. :P

I forgot to fix it in testing.

**Comment by unascribed** [comment]
FRICK, WRONG ISSUE
