### ISSUE TITLE
Satellite location textures won't update until clicked on

### ISSUE THREAD

**Issue by SpartanSamuel** [elytra/CorrelatedPotentialistics#17]
I have a satellite location that's accessing the inventory of my main base remotely. However, whenever power is lost to it, or restored to it, the textures don't update to reflect their loss / gain of power until I right click on them. It's a small issue because all of the functionality is as intended, just a visual issue.

[Loss](https://youtu.be/8CaXAFIU9ns)

[Gain](https://youtu.be/zZZAMgwil00)

**Comment by unascribed** [comment]
That's... strange. It's probably related to the changes in block syncing in 1.9.4.

**Comment by SpartanSamuel** [comment]
Ah, the block syncing changed between 1.8.9 and 1.9.4? My details are below, sorry for not including them before.

MC: 1.8.9
Forge: 11.15.1.1855
CoPo: 0.2.3_01

**Comment by unascribed** [comment]
I can't seem to reproduce this.
