### ISSUE TITLE
power problem

### ISSUE THREAD

**Issue by CraftYourWay** [elytra/CorrelatedPotentialistics#23]
ok here is the problem, i connect about 8 server with full 64k disks, i connect an creative capacitor bank to it from the mod enderio, so at first the controller block turns on, then after the 10 second boot, it turns off and wont turn on, so i added 2 more of those capacitor blocks snd it turns on again with all the servers, then after a bit of time when the rf within the controller is above 10000 or 20000 rf the block gets red. and does not work anymore, de server are still on in this case but not accesable, how can i fix this, an enderio creative capacitor block outputs 500 000 rf, so it should not nag about not anough power.

**Comment by unascribed** [comment]
The controller has a hard limit of 320 RF/t, and having tons of 64k drives will hit the limit extremely quickly.

You'll want to make a smaller network or use smaller drives.

**Comment by CraftYourWay** [comment]
i would like a big network, prefer 1 server room then 10 smaller ones. but thnx for the info

**Comment by unascribed** [comment]
Yes, but one of the things that a lot of people miss is that smaller drives are *better*. With big drives, you usually run out of types before bytes, which is a waste. If you're using the system to store a lot of a few kinds of items, then it's worth it. Otherwise, it's best to use 4k or 1k drives.

**Comment by CraftYourWay** [comment]
ok then ill try that maybe an id to add something to get more power idk wel thnx for the info :)
