### ISSUE TITLE
[1.8.9] Console spam

### ISSUE THREAD

**Issue by SirAzazel** [elytra/CorrelatedPotentialistics#24]
So trying to lookup what was causing server lag i looked in console and all i see is that:
![srjo2ka](https://cloud.githubusercontent.com/assets/5310658/16180268/589ae732-3689-11e6-99b7-52256423864d.png)

Still i dont think that is a lag cause, but being unable to see console is not that great.
CP-0.2.2_01

**Comment by unascribed** [comment]
My guess is something is thrashing chunk loads. (Maybe someone has a chunk loader that doesn't cover their entire base?)

I'll try to make that debug message less annoying.
