### ISSUE TITLE
Wireless terminal preferences are not saved

### ISSUE THREAD

**Issue by SpartanSamuel** [elytra/CorrelatedPotentialistics#26]
Any time that I go into the terminal, wirelessly or via the block, the default search parameters are via Quantity and Descending. Could this be changed to configure itself to the last search parameter I performed? For example, if I search alphabetically / ascending and then I exit, when I enter the terminal again I'd still like it to search that way.

**Comment by unascribed** [comment]
(1 is a bug, 2 and 3 are feature requests)

**Comment by SpartanSamuel** [comment]
Ah! My mistake, sorry about that.

**Comment by unascribed** [comment]
It's not your mistake, for something you didn't design it's impossible to tell if a given thing is missing or broken. In this case, it's broken. :P

**Comment by unascribed** [comment]
Can't reproduce the first one. Keep in mind those preferences are stored per-item and per-block, and are unique for each player.

**Comment by unascribed** [comment]
Are you still having the first issue? If so, could you include a screenshot or similar of your setup so I can try to reproduce the issue?

**Comment by SpartanSamuel** [comment]
I'm currently away on business, but return home next weekend. I'll double check and, if the issue persists, ready up screenshots if not a short video.

**Comment by unascribed** [comment]
Are you still having this issue?

**Comment by SpartanSamuel** [comment]
Yes, the issue persists. Thank you for your patience on my response, btw, I really appreciate it.

It bears noting that this only occurs with the Wireless Terminal. The Terminal block remembers my last search method including the search text. The Wireless Terminal remembers neither.

I'll make a post in a few minutes when I edit the video and upload it to YouTube.

**Comment by SpartanSamuel** [comment]
https://youtu.be/hULbetNE98c

**Comment by unascribed** [comment]
Aha, so this is an issue with the wireless terminal. I think I may know why.
