### ISSUE TITLE
Stack smearing consumes items in Interface config

### ISSUE THREAD

**Issue by SpartanSamuel** [elytra/CorrelatedPotentialistics#28]
Specifically, when I have something held in my hands. When I open the GUI with an empty hand, the items leave a ghost image just fine.

EDIT: Well, I thought that was it, but now it's random at best. I'll try to snag a video of it happening to help narrow it down when I can. It appears to be time based, as I can usually put in seven or so of the slots before an item's just taken into the ether forever.

MC: 1.8.9
Forge: 11.15.1.1875
CP: 0.2.3_01

**Comment by unascribed** [comment]
Are you still having this issue? If so, could you include reproduction instructions? (Also, are you left-clicking or right-clicking? That could be the problem)

**Comment by SpartanSamuel** [comment]
AAAAAAHHH! Man, you're the most patient person ever. Thanks so much for not just closing the ticket, hehe. I've logged in and am testing now.

**Comment by SpartanSamuel** [comment]
I can't imagine having switched left and right clicks when I was originally having the issue, but currently the item only disappears when I right click as I'm actually placing the item in the slot instead of ghosting as when I left click. This is regardless of my hands being full or empty.

**Comment by unascribed** [comment]
Okay, thought so. Right clicks are known to be iffy in my fake slots.

**Comment by unascribed** [comment]
Nope, this is related to stack smearing. Happens with left and right click.
