### ISSUE TITLE
Inserting a drive into drive bay crashes MC

### ISSUE THREAD

**Issue by ericcotelnu** [elytra/CorrelatedPotentialistics#30]
[crash-2016-08-01_22.26.53-server.txt](https://github.com/elytra/CorrelatedPotentialistics/files/395143/crash-2016-08-01_22.26.53-server.txt)

MC: 1.10.2
Mod version: latest (1.1.3)
Forge: latest supported (12.18.1.2044)

**Comment by unascribed** [comment]
Temporary fix: remove all wireless receivers/transmitters on your system.

**Comment by unascribed** [comment]
The fix I pushed is kind of dumb, could you include a screenshot or similar of your system so I can reproduce it locally and fix it for real?

**Comment by unascribed** [comment]
Closing this issue due to no response in a month.
