### ISSUE TITLE
Minecraft crashes on startup

### ISSUE THREAD

**Issue by LordFifth** [elytra/CorrelatedPotentialistics#31]
[crash-2016-08-14_16.25.08-client.txt](https://github.com/elytra/CorrelatedPotentialistics/files/417235/crash-2016-08-14_16.25.08-client.txt)
With no other mods on a fresh install on 1.10.2, forge-1.10.2-12.18.1.2063, and Correlated Potentialistics 1.1.3. I also tested on minecraft version 1.9.4 and 1.8.6 to be sure. I also tested whether I could run modded without Correlated Potentialistics and it was fine. I hope to see fix soon as from what I could see (especially the gui less drive bay) this seems to be shaping up to a very polished and stylish mod!

**Comment by jamierocks** [comment]
Please upload the log to Gist

**Comment by LordFifth** [comment]
[Crash Gist](https://gist.github.com/LordFifth/f7f4637fcfaa3e9907f910a043c23836)

**Comment by unascribed** [comment]
You need to install a mod that bundles the RF API. CoPo does not do this itself.
