### ISSUE TITLE
[1.10.2] CorrelatedPotentialistics causing a crash with Sponge.

### ISSUE THREAD

**Issue by LuxusDarkangel** [elytra/CorrelatedPotentialistics#32]
Using the Partitioning mode button in a server running SpongeForge will crash it (Crash report: https://gist.github.com/LuxusDarkangel/0a70ae544cd508afc13ced14ae7dbbdf)

One of the developers pointed at this: https://github.com/elytra/CorrelatedPotentialistics/blob/637322cd00aec0aee1e70528a2010a5c98a090ed/src/main/java/io/github/elytra/copo/inventory/ContainerDrive.java#L112

He's not sure why you want to create a slot with an index of -2000, but it's causing the issue.

**Comment by unascribed** [comment]
I create a slot with index -2000 because it's not a real slot.

I can work around this on my end I guess.

**Comment by LuxusDarkangel** [comment]
Don't want to bother you, but it will take you much time? This issue is driving me mad.

**Comment by unascribed** [comment]
The slot number is completely meaningless, and can be patched pretty trivially with a bytecode editor. Give me a minute.

**Comment by unascribed** [comment]
This modification should work: https://unascribed.com/f/b52c88f4_CorrelatedPotentialistics-1.1.3-spongefix.jar

**Comment by unascribed** [comment]
Keep in mind the containers in CoPo have a lot of overlapping slot indices due to most of them being fake slots, which could cause other strange behaviors on Sponge. I'll revamp the indices soon.

**Comment by LuxusDarkangel** [comment]
The patch works like a charm. This is the only bug with Sponge i've found so far, i'll wait for the indices revamp if I find another problem with them.

Thank you very much!
