### ISSUE TITLE
Number of items not displayed properly in Terminal.

### ISSUE THREAD

**Issue by vectorman1** [elytra/CorrelatedPotentialistics#33]
http://i.imgur.com/Ma4AEgh.png

This is the terminal I have with a few items, what happens is that with some items, as you can see there is no number attached as to how many of that specific item you've got.

I can't seem to find a specific pattern this is happening with, because as you can see, Stone is being displayed as 113  but then Cobblestone is not, but if I take a stack out of the Cobblestone, it becomes 96. If I put 5 extra 1 by 1 it becomes 101 as it should be.

Version is 0.1.2 on Minecraft 1.8.9. I am unable to test with a newer version as I am playing on a server, which is out of my control, check if the bug is present in newer versions.

**Comment by unascribed** [comment]
Your version of CoPo is quite out of date; this was fixed.

You'll have to get your server admin to update CoPo, preferably to v0.2.3_01.
