### ISSUE TITLE
Partial complete JEI Crafting

### ISSUE THREAD

**Issue by Ghezra** [elytra/CorrelatedPotentialistics#42]
When using the JEI button to pull to the crafting grid, allow the components that are in the system to be able to be pulled up for better display of which items are still needed to finish the crafting.

Some of the more complex recipes have many constructed components and searching explicitly for each and every one just to figure out which one is missing can be time consuming.

**Comment by unascribed** [comment]
Yeah, I've experienced this myself. Due to how the storage system works, using JEI's usual warning system would require a round-trip to the server, which could cause noticeable delay (i.e. the + button would be disabled while the mod waits for a response from the server)

**Comment by Ghezra** [comment]
Along the same train of thought,
Can you have JEI Crafting also pull from the player inventory, so if you've just made some sub components into your inventory, there isn't that 10 second confusion of 'wait, NOW why isn't this crafting working?'

I expect this would be somewhat mitigated by pulling the partial recipe as then you can see it was the things still in the player inventory.

**Comment by unascribed** [comment]
I was debating doing that, and decided to… and then promptly forgot. Whoops.

**Comment by unascribed** [comment]
Obsoleted by #39
