### ISSUE TITLE
Memory and Drive color coding on outer edge

### ISSUE THREAD

**Issue by Ghezra** [elytra/CorrelatedPotentialistics#43]
Currently the only way to see the type of drive is to be situated above the Drive/Memory bay.

Having  small band going up and down on the right hand side indicating the color/type of drive would be very helpful when the Bay's are closer to the ceiling.

**Comment by unascribed** [comment]
The tier indicator was more of a visual flair than anything, I didn't expect it to actually be useful for identification. You can name drives on an anvil, and a nametag will appear when you look at the drive.

**Comment by Ghezra** [comment]
True, but the color stripe is quick and easy visual identification at a glance without having to WAWLA over each drive. Just a quality of life thing :)
