### ISSUE TITLE
Auto restock crafting grid

### ISSUE THREAD

**Issue by MauveCloud** [elytra/CorrelatedPotentialistics#48]
In AE2, clicking the output of the crafting grid (when using a Crafting Terminal) would restock the crafting grid, unless there were no components in the system to craft the target item, or it was manually cleared.  In CoPo, the JEI + button has to be used each time, unless I want a full stack of the target item or something like that.  If I want to craft, for example, 9 of a given item, it's quite inconvenient.

I can manually place multiple components on the Terminal's crafting grid, but using Shift+click on the JEI "+" button only sets up for a single craft, and often transfers some other item to my inventory that I don't want.

**Comment by unascribed** [comment]
#39
