### ISSUE TITLE
Multiple boots of an identical network can increase the power consumption

### ISSUE THREAD

**Issue by MauveCloud** [elytra/CorrelatedPotentialistics#50]
I have the following blocks in my CoPo network:
1. a controller (32 T/t)
2. a terminal (4 T/t)
3. a memory bay (with a total of 9 KiB of memory at the moment, though afaik it draws 4 T/t regardless of how much memory is installed)
4. a drive bay with eight 4 MiB drives (8 T/t for the bay + 2 T/t per drive = 24 T/t)
That should be 64 T/t, right?

When I open the world (single-player), the controller shows a usage of 32 T/t before powering it (presumably since it hasn't scanned the network yet).  Once I power it up, the usage goes up to 64 T/t.  Okay so far.  However, when I turn off the power (in case it matters, I'm using a Forestry Electrical Engine upgraded with two "Electrical Boost II" (for a total of 100 RF/t output capability) and an Advanced Charging Battery in it), let the controller drain, then power it up again, the usage becomes 88 T/t.  Wait, what?  Where did the extra 24 T/t come from?  

If I have it in a backwards "L" shape to prevent multiple paths from the controller to other blocks (terminal above it, memory bay below, drive bay to the west of the memory bay, and engine to the east of the controller), it stays at 88 T/t even with repeated boots.  However, if I move the terminal to the west of the controller (to make a square shape), it can go up to 92 T/t.

**Comment by unascribed** [comment]
Weird. Could you include a screenshot of your setup, or a schematic/structure block save of it?

**Comment by MauveCloud** [comment]
Sure.  I took some screenshots before, but I wasn't certain they'd be necessary.  I'm adding one with the backwards "L" shape I tried that gets to 88 T/t, and I just took one with the square shape that gets to 92 T/t.
![2016-10-21_20 12 23](https://cloud.githubusercontent.com/assets/8942955/19617163/5ecc58e6-97de-11e6-956c-18162f84d903.png)
![2016-10-21_22 32 13](https://cloud.githubusercontent.com/assets/8942955/19617164/6427b0ba-97de-11e6-8f2b-2c1f2423d0a6.png)

**Comment by MauveCloud** [comment]
Additional note: I've tried changing the configs so that the energy costs are zero (just temporarily, until this bug is fixed), but it doesn't completely honor that: while booting up (such as when I first enter my single-player world), it draws 32 T/t, though once it finishes that, it changes to 0 T/t.  Also, when I come back after exploring or mining (far enough so that the chunk the Controller is in becomes unloaded), the Controller is usually completely drained, even though it had something like 22k T stored, which should have been enough for even a 20-second bootup cycle (at 32 T/t) once the chunk gets loaded again.

**Comment by unascribed** [comment]
Ah, yeah. I still have a few hardcoded energy values, like for booting.

The chunk loading thing is interesting, I'll have to look into it. It might just not be saving the energy value.
